### PR TITLE
routing: Add automatic failover

### LINKED ISSUE #45: Fall back to upstream database if query to ReadySet fails
**Brief Description of Feature:**
If a query to ReadySet fails, we should have it automatically fall back to the upstream database.

**Background:**
In case ReadySet is down or runs into an issue executing a query, the gem should fall back to running queries on the primary database.

**From the user's perspective:**
This should happen seamlessly from the user's perspective. We should also log a warning or something to ensure that it's not happening silently.

---
## Optional information to add

**Proposed Solution:**
This should only happen for **queries** and **not** for ReadySet SQL extensions (like `CREATE CACHE FROM`, etc.). Offhand, I'm not sure how we'd handle this. We'd need to somehow intercept the point at which the query is executed, wrap it in a `rescue`, and then execute the same query on a connection from the primary database's pool. One possibility is that we could create our own database adapter that wraps two postgres adapters: one connected to ReadySet and one connected to the upstream database. That would give us the access we need to intercept errors.

Another possibility is monkey patching the method in `ActiveRecord::Relation` that loads records, but this feels much less robust and more risky to me.

### PR DESCRIPTION
**Pull request by ethan-readyset**
This commit adds an optional automatic failover feature to the gem. If the number of connection errors to ReadySet exceeds a preconfigured threshold, ReadySet is considered to be unhealthy, all queries are routed upstream, and a background task is spawned that periodically checks ReadySet's health. When ReadySet is determined to be healthy again, the task is stopped, and queries are routed back to ReadySet.

Closes #45

### CODE REVIEW

**Comment by helpotters** [comment]
I'm still working through this PR.

I have also employed the use of various code analysis tools such as [skunk](https://github.com/fastruby/skunk) and [rubycritic](https://github.com/whitesmith/rubycritic).

Thanks to your code-review feedback, I'll try to keep the scope in-mind of our goal (v1 release).

File: lib/readyset/configuration.rb [hunk 1]
```diff
@@ -3,11 +3,20 @@
...
   class Configuration
-    attr_accessor :migration_path, :shard
+    attr_accessor :enable_failover, :failover_error_window_period, :failover_error_window_size,
+      :failover_healthcheck_interval, :migration_path, :shard
 
     def initialize
+      @enable_failover = false
+      @failover_healthcheck_interval = 5.seconds
+      @failover_error_window_period = 1.minute
+      @failover_error_window_size = 10
```
Comment (helpotters) [inline lib/readyset/configuration.rb:13]: **_suggestion:_** What do you think about a team-up for this collection of parameters? 

image

--- 

It seems like all of these options depend on each other. An abstraction that "summarizes" them could help out! `automatic_fallover_config_options`

File: lib/readyset/health/healthchecks.rb [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+      # ReadySet is connected to the upstream database.
+      #
+      # @return [Boolean] whether ReadySet is healthy
+      def healthy?
+        connection.execute('SHOW READYSET STATUS').any? do |row|
+          row['name'] == 'Database Connection' && row['value'] == 'Connected'
+        end
+      rescue
+        false
+      end
```
Comment (helpotters) [inline lib/readyset/health/healthchecks.rb:20]: **_thought:_** At a glance, this seems closer to a parser :eyeglasses: than a :heavy_check_mark: healthcheck. 

Do you think `row` would be considered referencing something "outside" of the `Healthchecks` object?

**Review by helpotters — CHANGES_REQUESTED** [review]
I've been reading up on some refactoring stuff! Let me know what you think about my suggestions here. Mostly nitpicks. Everything else seems great, let me know if you found any friction in the specs that I should double-check.

File: lib/readyset/health/healthchecker.rb [hunk 3]
```diff
@@ -0,0 +1,125 @@
...
+      end
+
+      def is_readyset_connection_error?(exception)
+        if exception.cause
+          is_readyset_connection_error?(exception.cause)
+        else
+          UNHEALTHY_ERRORS.any? { |e| exception.is_a?(e) } &&
+            exception.is_a?(Readyset::Error)
+        end
+      end
```
[the remark this answers is not in the document]
Comment (ethan-readyset) [reply lib/readyset/health/healthchecker.rb:114]: I typically avoid trailing conditionals and prefer standard `if ... else` statements. IMO they read a bit easier, but I think it's just a matter of opinion 🤷

File: lib/readyset/health/healthchecker.rb [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+
+      def disconnect_readyset_pool!
+        ActiveRecord::Base.connected_to(shard: shard) do
+          ActiveRecord::Base.connection_pool.disconnect!
+        end
+      end
+
+      def is_readyset_connection_error?(exception)
+        if exception.cause
+          is_readyset_connection_error?(exception.cause)
```
[the remark this answers is not in the document]
Comment (ethan-readyset) [reply lib/readyset/health/healthchecker.rb:109]: I don't think we have to worry -- the exception.cause field is populated when an exception is `rescue`d and another one `raise`d in its place, and I can't see that happening so many times that it causes a stack overflow

File: lib/readyset/health/healthchecks.rb (hunk 2 above)
Comment (ethan-readyset) [reply lib/readyset/health/healthchecks.rb:20]: Hmm I'm not sure I follow -- can you expound a bit?

The health is being checked by ensuring that 1) we can successfully connect to ReadySet and run `SHOW READYSET STATUS` and 2) ReadySet is connected to the upstream database as expected

File: lib/readyset/health/healthchecker.rb [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+module Readyset
+  module Health
+    # Processes the given exceptions to determine whether ReadySet is currently unhealthy. If
+    # ReadySet is indeed unhealthy, a background task is spawned that periodically checks
+    # ReadySet's health directly until a healthy state has been restored. While ReadySet is in an
+    # unhealthy state, `Healthchecker#healthy?` will return false.
+    class Healthchecker
+      UNHEALTHY_ERRORS = [::PG::UnableToSend, ::PG::ConnectionBad].freeze
+
+      def initialize(healthcheck_interval:, error_window_period:, error_window_size:, shard:)
```
[the remark this answers is not in the document]
Comment (ethan-readyset) [reply lib/readyset/health/healthchecker.rb:15]: Makes sense to me! Though I think I'd prefer to leave the instance variables the way they are -- I think it makes it clearer what attributes are available on the class

File: lib/readyset/configuration.rb (hunk 1 above)
Comment (ethan-readyset) [reply lib/readyset/configuration.rb:13]: Makes sense to me!

**Comment by ethan-readyset** [comment]
@helpotters Thanks for the great suggestions! Addressed the comments and rebased, so this is ready for another pass

File: lib/readyset/configuration.rb [hunk 6]
```diff
@@ -3,18 +3,26 @@
...
-    attr_accessor :enable_failover, :failover_error_window_period, :failover_error_window_size,
-      :failover_healthcheck_interval, :migration_path, :shard
+    attr_accessor :migration_path, :shard
 
     def initialize
-      @enable_failover = false
-      @failover_healthcheck_interval = 5.seconds
-      @failover_error_window_period = 1.minute
-      @failover_error_window_size = 10
       @migration_path = File.join(Rails.root, 'db/readyset_caches.rb')
```
Comment (helpotters) [inline lib/readyset/configuration.rb:9]: **:sunglasses::_** Moving the parameters to a `failover` method really represents the underlying behavior in a clean way. 

I could definitely learn from you in regards to how you're anticipating these sorts of caveats!

File: lib/readyset/health/healthchecker.rb [hunk 7]
```diff
@@ -12,14 +12,16 @@ module Health
     class Healthchecker
       UNHEALTHY_ERRORS = [::PG::UnableToSend, ::PG::ConnectionBad].freeze
 
-      def initialize(healthcheck_interval:, error_window_period:, error_window_size:, shard:)
+      def initialize(config, shard:)
         @healthy = Concurrent::AtomicBoolean.new(true)
-        @healthcheck_interval = healthcheck_interval
+        @healthcheck_interval = config.healthcheck_interval!
```
Comment (helpotters) [inline lib/readyset/health/healthchecker.rb:17]: **_question_** _(non-blocking)_ Where did the change to a `bang!` method emerge from?

File: lib/readyset.rb [hunk 8]
```diff
@@ -146,9 +146,7 @@ class << self
 
   def self.healthchecker
     @healthchecker ||= Readyset::Health::Healthchecker.new(
-      healthcheck_interval: config.failover_healthcheck_interval,
-      error_window_period: config.failover_error_window_period,
-      error_window_size: config.failover_error_window_size,
+      config.failover,
```
Comment (helpotters) [inline lib/readyset.rb:149]: :+1: :rocket:

**Review by helpotters — APPROVED** [review]
This PR was definitely a learning experience for me!

File: lib/readyset/configuration.rb (hunk 6 above)
Comment (ethan-readyset) [reply lib/readyset/configuration.rb:9]: It was your suggestion that prompted the refactor, so thank you 😄

File: lib/readyset/health/healthchecker.rb (hunk 7 above)
Comment (ethan-readyset) [reply lib/readyset/health/healthchecker.rb:17]: @helpotters The bang comes from `ActiveSupport::OrderedOptions`: https://api.rubyonrails.org/classes/ActiveSupport/OrderedOptions.html

Using a bang throws an exception if that option is not set
